---
- hosts: "{{ selected_hosts | default('osx') }}"

  gather_facts: true

  vars_files:
    - ./vars/project.yml

  pre_tasks:
    - shell: echo "ansible starting at {{ ansible_date_time.iso8601 }} for {{ ansible_nodename }}" | wall

  roles:
    - { role: harden, tags: harden }
    - { role: ruby, tags: ruby, version: "{{ ruby_version }}" }
    - { role: rubygems, tags: ruby, gems: "{{ install_gems }}" }
    - { role: homebrew, tags: homebrew, brews: "{{ install_brews }}" }
    - { role: direnv, tags: direnv, version: "{{ ruby_version }}" }

  post_tasks:
    - shell: echo "ansible finished at {{ ansible_date_time.iso8601 }} for {{ ansible_nodename }}" | wall
