---
- hosts: "{{ selected_hosts | default('crs') }}"

  gather_facts: true

  vars_files:
    - ./vars/project.yml

  pre_tasks:
    - shell: echo "starting at {{ ansible_date_time.iso8601 }}" | wall

  roles:
    - { role: rubygems, tags: rubygems }
    - { role: homebrew, tags: homebrew }
    - { role: direnv, tags: direnv }

  post_tasks:
    - shell: echo "done at {{ ansible_date_time.iso8601 }}" | wall
