---
- template: src=direnvrc.j2 dest={{ ansible_env.HOME }}/.direnvrc mode='u=rw,g=r,o=r'

- file: path={{ ansible_env.HOME }}/.envrc state=touch mode='u=rw,g=r,o=r'

- name: direnv allow home
  shell: direnv allow {{ ansible_env.HOME }}
  register: _direnv_allow
