---
- name: configure git push.default
  shell: git config --global push.default simple
  changed_when: False

- name: configure git user.name
  shell: git config --global user.name "{{ name }}"
  changed_when: False

- name: configure git user.email
  shell: git config --global user.email "{{ email }}"
  changed_when: False
