---
- debug: msg="{{ brews }}"
- homebrew: update_homebrew=yes upgrade_all=yes
  when: brew_update == True

#- homebrew: name=foo state=head
#- homebrew: name=foo state=linked
#- homebrew: name=foo state=absent
#- homebrew: name=foo,bar state=absent

- include: git.yml name={{ user_name }} email={{ user_email }}

- homebrew: name=chromium state=linked install_options=with-exec-script
- homebrew: name=curl state=present install_options=with-libressl
- homebrew: name=openssh state=present install_options=with-keychain-support,with-ldns
- homebrew: name=python state=present install_options=without-gdbm,without-sqlite


# TODO: cask
    #launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.syncthing.plist
    #launchctl load ~/Library/LaunchAgents/homebrew.mxcl.syncthing.plist

- name: install brews
  shell: brew install {{ item }}
  with_items: "{{ brews }}"
