---
- name: check bash (http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2014-7169)
  shell: bash -c "env x='() { :;}; echo vulnerable' bash -c \"echo this is a test\""
  register: result
  failed_when: result.stdout != 'this is a test'
  tags: cve

- name: create sysctl.conf
  file: path=/etc/sysctl.conf state=touch owner=root group=wheel mode='u=rw,g=r,o=r'
  sudo: True

- sysctl: name=net.link.ether.inet.arp_unicast_lim value=0 sysctl_set=True state=present
  sudo: True
